### ISSUE TITLE
Table tx_dpf_domain_model_documenttype can't be created in MySQL 5.7 because 'virtual' is now reserved

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-publication#110]
MySQL added `virtual` as [reserved word](https://dev.mysql.com/doc/refman/5.7/en/keywords.html) in version 5.7.6. In effect, the table `tx_dpf_domain_model_documenttype` can't be created via extension installation from this version on.

EDIT:
https://dev.mysql.com/doc/refman/5.7/en/keywords.html#keywords-5-7-detailed-V
VIRTUAL (R); added in 5.7.6 (reserved)

**Comment by claussni** [comment]
Solution would be to rename the model field `virtual` to something expressing the fact that document types which this flag do need to have attachments. What do think, @haogatyp?

**Comment by haogatyp** [comment]
I would suggest to rename it into type_abstract.

**Comment by claussni** [comment]
What happens to existing data when renaming the field?

**Comment by haogatyp** [comment]
The database field is also renamed. When updating the extension, the migration of the field must then be initiated via Installation Tool->Database compare (Alter Table). If this is not possible, a separate update script must be developed.

**Comment by haogatyp** [comment]
In the Fedora repository, the field should certainly not be renamed, so you do not have to migrate. Therefore, it might be better to change the field in TYPO3 to type_virtual. So it remains traceable in the code, regarding the interface between TYPO3 and repository.

**Comment by claussni** [comment]
TYPO3 database analyzer tool option does not seem to be very helpful:
>ALTER TABLE tx_dpf_domain_model_documenttype CHANGE virtual zzz_deleted_virtual tinyint(1) unsigned NOT NULL default '0';

**Comment by claussni** [comment]
I consider MySQL 5.7 support an enhancement. Given the necessary code changes and data migration issues it's actually not an easy fix to do.

**Comment by claussni** [comment]
Suggestion:
1. Release providing an update script for running on MySQL 5.6 for moving the field.
2. Next release removing the problematic field definition.

**Comment by claussni** [comment]
@haogatyp Can we address this issue now for 4.x and later provide migration for 3.x branches?

**Comment by haogatyp** [comment]
Yes, this should be possible.
