### ISSUE TITLE
Hardcoded base URL in Emails should be removed

### ISSUE THREAD

**Issue by Erikmitk** [kitodo/kitodo-publication#164]
https://github.com/kitodo/kitodo-publication/blob/374980744146d127f3cbd3860b74b273c26ce1d7/Classes/Services/Email/Notifier.php#L66

https://github.com/kitodo/kitodo-publication/blob/374980744146d127f3cbd3860b74b273c26ce1d7/Classes/Services/Email/Notifier.php#L144

https://github.com/kitodo/kitodo-publication/blob/50ae565ba836317af4ef57dcd3285b90812916d3/Classes/Plugins/RelatedListTool/RelatedListTool.php#L92

**Comment by claussni** [comment]
This URL does not need to be generated. It's there for historical reasons. Better to use the marker ###URN### and generate a proper HTML Link.

**Comment by Erikmitk** [comment]
Yes, but the `RelatedListTool`-plugin only need the additional `s`. That has nothing to do with the Emails.
