### ISSUE TITLE
TYPO3 Update

### ISSUE THREAD

**Issue by Epoche-Napoleon** [kitodo/kitodo-publication#271]
That sounds like an exciting solution. However, TYPO3 9.5LTS has become somewhat outdated in the meantime and is only available with paid support.

Is an update to a newer TYPO3 11.5/12.4 planned?

**Comment by Epoche-Napoleon** [comment]
Many thanks for the feedback. It's a shame that there is no future for TYPO3 here.
How time-consuming would the TYPO3 update be?

**Comment by claussni** [comment]
I think it would go much smoother than the previous upgrade from v7. We might do this, but it's not scheduled in any way at the moment. You are welcome to provide PRs that go in this direction! :wink:
