### ISSUE TITLE
Missing license statement

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-publication#60]
The project includes many files with a license header, but I did not find any information on the license used by the whole project. Is it GPL2 / GPL2+ / GPL3 / GPL3+?

I suggest to add a license file in the standard form which is recognized by GitHub and other tools.

**Comment by claussni** [comment]
@albig What is the standard procedure for licensing of TYPO3 extensions?

**Comment by albig** [comment]
That's not only related to TYPO3. The LICENCE.txt file is missing. See https://help.github.com/articles/licensing-a-repository/. We should put the same as in Kitodo.Presentation.

**Comment by stweil** [comment]
According to https://typo3.org/index.php?id=782, GPL2+ seems to be the right choice. GPL3 / GPL3+ are compatible to GPL2+, so I think that using them would also be possible.

Obviously TYPO3 documentation requires a different license, see https://forge.typo3.org/issues/46163.

**Comment by stweil** [comment]
I think that using the same license (GPL3) as for [Kitodo.Presentation](https://github.com/kitodo/kitodo-presentation) would be reasonable.

**Comment by stweil** [comment]
Thanks a lot.
