### ISSUE TITLE
Cleanup TCA-configuration

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-publication#65]
The TCA files should be placed in Configuration/TCA/tx_tablename.php. Currently a part is located in ext_tables.php and is loaded by dynamicConfigFile from Configuration/TCA/Modelname.php. This is deprecated and will be dropped in TYPO3 8.x.

The solution is simple, is working with TYPO3 6.2 already and could speed up the caching of the TCA-configuration.

Background: 

- https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Deprecation#Deprecation:_.2370514_-_dynamicConfigFile_is_deprecated
- https://usetypo3.com/good-practices-in-extensions.html

**Comment by claussni** [comment]
Since you assigned this TCA issue to yourself, maybe you want to take over #66 as well?
