### ISSUE TITLE
Change wizard configuration in TCA

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-publication#66]
From deprecation.log:

`The way registering a wizard in TCA has changed in 6.2. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. The possibility to register wizards this way will be removed in TYPO3 CMS 7.`

As Kitodo.Publication should be already compatible with TYPO3 7.6, this is a bug.

**Comment by claussni** [comment]
Where can I find this TCA?

**Comment by albig** [comment]
There is only one TCA which uses these wizards. It's located at `Configuration/TCA/MetadtaPage.php`
