### ISSUE TITLE
Check and Remove ext_typoscript_setup.txt

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-publication#67]
IMHO the file ext_typoscript_setup.txt can be removed safely.

The only setting, which is not default is `config.tx_extbase.persistence.updateReferenceIndex = 0`. But this shouldn't hurt.

https://github.com/kitodo/kitodo-publication/blob/251e2e9b72f2dd0976ceb54a91c39680adcf70f7/ext_typoscript_setup.txt#L17

**Comment by claussni** [comment]
What is/was the purpose of this file?

**Comment by albig** [comment]
I noticed now the setting `config.tx_extbase.persistence.updateReferenceIndex` is false by default. So no setting in this file changes anything. We can delete it safely.

> Internally, TYPO3 manages an index of all relationships between two datasets the so-called RefIndex. Due to this index it's possible to show the number of associated datasets in the list module's column [Ref.]. By clicking on the number you get further informations about the incoming and outgoing references of the dataset. This index is automatically updated when any datasets get edited. The configuration config.tx_extbase.persistence.updateReferenceIndex = 1 effects an update when datasets get edited in the Frontend though it is normally deactivated due to its huge effects on performance.
https://docs.typo3.org/typo3cms/ExtbaseFluidBook/6-Persistence/2-configure-the-backends-inputforms.html

**Comment by claussni** [comment]
Resolved in #82
