### ISSUE TITLE
Verify TYPO3 7.6 compatibility and fix dependency

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-publication#68]
The extension should be compatible with TYPO3 7.6 LTS as no other LTS is supported by TYPO3 anymore.

Verify the compatibility and add the right dependancy to ext_emconf.php. Probably "typo3 => 6.2.0 - 7.6.99".

**Comment by claussni** [comment]
How to verify this?

**Comment by albig** [comment]
We only can do functional tests and check the deprecation log. With next pull-request, the backend and frontend are working. We should test the full workflow somehow.

**Comment by claussni** [comment]
I've merged #89. Functional tests you mentioned can start, I guess...
