### ISSUE TITLE
Publication depends on static_info_tables and breaks if no sys_language is set

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-publication#75]
On installation of Kitodo.Publication in TYPO3 6.2 or 7.6 the backend module "Admin" does not work if 

1. The tables of extension static_info_tables are not present
2. No sys_language is set in root folder

**Comment by claussni** [comment]
@haogatyp Is the language table generation feature really needed? Or can it be replaced with a default table containing a subset of languages?

**Comment by haogatyp** [comment]
That should be possible. I think the idea in using static_info_tables was to do it 
the "TYPO3 way", at least as I understood it in the past.

**Comment by claussni** [comment]
@albig What do you think?
